-- India-only DB cleanup (manual).
--
-- Prefer the FK-safe Python helper (deletes dependent rows in the correct order):
--   PYTHONPATH=. python3 scripts/purge_non_indian_stocks.py
--   PYTHONPATH=. python3 scripts/purge_non_indian_stocks.py --execute
--
-- Raw SQL is unsafe unless every FK from child tables to stocks.id is cleared first.
-- Preview exchanges:
--   SELECT UPPER(exchange) AS ex, COUNT(*) FROM stocks GROUP BY 1 ORDER BY 2 DESC;
